### ISSUE TITLE
Endless "Creating Asset" Message & "Forbidden" Error with AlgoSigner

### ISSUE THREAD

**Issue by 1Jenna** [algodesk-io/algodesk.io#10]
I have been trying to create an ASA in Algodesk mainnet with AlgoSigner for 2 days now, with no success. Every time I attempt to create the asset, the “creating asset” message runs endlessly and it will not create the ASA.

Since last night, I can’t even get as far as the “creating asset” message, and the words “forbidden” appear, no matter what I do.

I would be thankful for some help.  Others are also reporting this issue on Reddit.

**Comment by fridas1234** [comment]
I’m having the same problem. I’ve been trying to create an NFT & constantly keep getting an error. Anyone know how to go about this?

**Comment by algodesk-io** [comment]
This is fixed in new version that is going to be released next week. thanks for reporting
