### ISSUE TITLE
Getting error on asset creation using defaults. at algodesk.io

### ISSUE THREAD

**Issue by rfustino** [algodesk-io/algodesk.io#15]
{"message":"TransactionPool.Remember: transaction LVJDIA3UNNHJXJYEPDXCPAUJESFBSTU2OOC3B4FPSWC2RU6ATXPA: account ZHKAFJY5CDRDZKLW72JJBMT277D2TFZZ6G6BNJA7FJICQY5EJRQ5L6VR5M balance 29614000 below min 29655000 (271 assets)"}

**Comment by algodesk-io** [comment]
Default account was on low balance. it is working after adding algos.
