### ISSUE TITLE
When I Try To Make A Transaction

### ISSUE THREAD

**Issue by StishSits** [algodesk-io/algodesk.io#3]
When I Try To Make A Transaction This Console Error Pops Up. 
this.getIndexer(...).getAssetByID is not a function

![screenshot-teal algodesk io-2021 02 23-00_04_39](https://user-images.githubusercontent.com/77869708/108807793-d6766a80-756a-11eb-8861-797ddb66d950.png)

**Comment by algodesk-io** [comment]
Thanks for reporting . We will fix this in a week.

**Comment by headline-dev** [comment]
I'm having this same issue. Totally unable to use ASAs in the transaction modal. Do we have a timeline on this fix yet?

**Comment by algodesk-io** [comment]
This issue is fixed and deployed.
